Repository HackerThon-The7/HackerThon-Android-16TH, pull requests merged in 2022-10, with the labels that each got.

#2 🔀 :: (#1) issue & pr 템플릿 추가
  .github/ISSUE_TEMPLATE/do.yml
  .github/ISSUE_TEMPLATE/fix.yml
  .github/Pull_Request_Template.yml
Labels: good first issue

#8 🔀 :: notoSansKr들들들 폰트 추가
  .idea/misc.xml
  app/src/main/res/font/noto_sans_kr_black.ttf
  app/src/main/res/font/noto_sans_kr_bold.ttf
  app/src/main/res/font/noto_sans_kr_light.ttf
  app/src/main/res/font/noto_sans_kr_medium.ttf
  app/src/main/res/font/noto_sans_kr_regular.ttf
  app/src/main/res/font/noto_sans_kr_thin.ttf
Labels: enhancement

#10 🔀 :: (#9) package 구조 작성
  app/src/main/java/com/yongjincompany/hackerthonandroid/common/.gitkeep
  app/src/main/java/com/yongjincompany/hackerthonandroid/features/addinfo/database/dao/.gitkeep
  app/src/main/java/com/yongjincompany/hackerthonandroid/features/addinfo/database/entity/.gitkeep
  app/src/main/java/com/yongjincompany/hackerthonandroid/features/addinfo/view/.gitkeep
  app/src/main/java/com/yongjincompany/hackerthonandroid/features/addinfo/vm/.gitkeep
  app/src/main/java/com/yongjincompany/hackerthonandroid/features/dictionary/database/dao/.gitkeep
  app/src/main/java/com/yongjincompany/hackerthonandroid/features/dictionary/database/entity/.gitkeep
  app/src/main/java/com/yongjincompany/hackerthonandroid/features/dictionary/view/.gitkeep
  app/src/main/java/com/yongjincompany/hackerthonandroid/features/dictionary/vm/.gitkeep
  app/src/main/java/com/yongjincompany/hackerthonandroid/features/home/database/dao/.gitkeep
  app/src/main/java/com/yongjincompany/hackerthonandroid/features/home/database/entity/.gitkeep
  app/src/main/java/com/yongjincompany/hackerthonandroid/features/home/view/.gitkeep
  app/src/main/java/com/yongjincompany/hackerthonandroid/features/home/vm/.gitkeep
  app/src/main/java/com/yongjincompany/hackerthonandroid/features/main/database/dao/.gitkeep
  app/src/main/java/com/yongjincompany/hackerthonandroid/features/main/database/entity/.gitkeep
  app/src/main/java/com/yongjincompany/hackerthonandroid/features/main/view/.gitkeep
  app/src/main/java/com/yongjincompany/hackerthonandroid/features/main/vm/.gitkeep
  app/src/main/java/com/yongjincompany/hackerthonandroid/features/nfc/.gitkeep
  app/src/main/java/com/yongjincompany/hackerthonandroid/features/profile/database/dao/.gitkeep
  app/src/main/java/com/yongjincompany/hackerthonandroid/features/profile/database/entity/.gitkeep
  app/src/main/java/com/yongjincompany/hackerthonandroid/features/profile/view/.gitkeep
  app/src/main/java/com/yongjincompany/hackerthonandroid/features/profile/vm/.gitkeep
  app/src/main/java/com/yongjincompany/hackerthonandroid/features/tip/database/dao/.gitkeep
  app/src/main/java/com/yongjincompany/hackerthonandroid/features/tip/database/entity/.gitkeep
  app/src/main/java/com/yongjincompany/hackerthonandroid/features/tip/view/.gitkeep
  app/src/main/java/com/yongjincompany/hackerthonandroid/features/tip/vm/.gitkeep
Labels: enhancement

#11 🔀 :: 정보 작성 페이지 UI 구현
  .idea/misc.xml
  app/src/main/res/drawable/edit_back.xml
  app/src/main/res/drawable/gender_btn_back.xml
  app/src/main/res/drawable/ic_back.xml
  app/src/main/res/drawable/ic_recyle.png
  app/src/main/res/layout/fragment_add_info.xml
  app/src/main/res/layout/fragment_add_info_girl.xml
Labels: enhancement

#13 🔀 :: 새로고침 아이콘 svg로 바꾸기
  .idea/gradle.xml
  .idea/misc.xml
  app/build.gradle.kts
  app/src/main/res/drawable/ic_recyle.png
  app/src/main/res/drawable/ic_refresh.xml
  app/src/main/res/layout/fragment_add_info_girl.xml
Labels: enhancement

#18 🔀 :: readme 작성
  README.md
Labels: documentation

#20 🔀 :: Version 분리
  buildSrc/src/main/kotlin/Dependency.kt
  buildSrc/src/main/kotlin/Version.kt
Labels: enhancement

#23 🔀 :: BaseFragment 작성
  app/src/main/java/com/yongjincompany/hackerthonandroid/base/BaseFragment.kt
Labels: enhancement

#37 🔀 :: 매우 치명적인 오류 해결
  .idea/misc.xml
  app/src/main/res/layout/activity_calendar.xml
  buildSrc/build/libs/buildSrc.jar
Labels: bug

#39 🔀 :: 채팅 - 메뉴 화면 UI 구현
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/yongjincompany/hackerthonandroid/features/chat/view/ChatActivity.kt
  app/src/main/res/drawable/edit_chatting_back.xml
  app/src/main/res/layout/activity_chat.xml
Labels: enhancement

#44 🔀 :: (#32) - 생리 유형 확인 후 값 전송
  .idea/misc.xml
  .idea/vcs.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/yongjincompany/hackerthonandroid/features/mt/database/entity/MenstrualExaminationData.kt
  app/src/main/java/com/yongjincompany/hackerthonandroid/features/mt/view/PeriodExaminationActivity.kt
  app/src/main/java/com/yongjincompany/hackerthonandroid/features/mt/view/adapter/MenstrualExaminationAdapter.kt
  app/src/main/java/com/yongjincompany/hackerthonandroid/features/mt/view/fragment/PeriodExaminationFragment.kt
  app/src/main/java/com/yongjincompany/hackerthonandroid/features/mt/vm/PeriodExaminationViewModel.kt
  app/src/main/res/layout/activity_period_examination.xml
  app/src/main/res/layout/fragment_period_examination.xml
  app/src/main/res/layout/item_question.xml
  buildSrc/build/kotlin/buildSrcjar-classes.txt
  buildSrc/build/kotlin/compileKotlin/build-history.bin
  buildSrc/build/kotlin/compileKotlin/caches-jvm/inputs/source-to-output.tab
  buildSrc/build/kotlin/compileKotlin/caches-jvm/inputs/source-to-output.tab.keystream
  buildSrc/build/kotlin/compileKotlin/caches-jvm/inputs/source-to-output.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/inputs/source-to-output.tab_i
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/class-fq-name-to-source.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/internal-name-to-source.tab.values.at
  buildSrc/build/kotlin/compileKotlin/caches-jvm/jvm/kotlin/source-to-classes.tab.keystream
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/file-to-id.tab.keystream
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/file-to-id.tab_i
  buildSrc/build/kotlin/compileKotlin/caches-jvm/lookups/id-to-file.tab.values.at
  buildSrc/build/kotlin/compileKotlin/last-build.bin
  buildSrc/build/libs/buildSrc.jar
  buildSrc/build/pluginUnderTestMetadata/plugin-under-test-metadata.properties
  buildSrc/build/source-roots/buildSrc/source-roots.txt
Labels: enhancement

#47 🔀 :: 생리 시작 및 끝 일정 DB에 추가, 조회하기
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/yongjincompany/hackerthonandroid/database/entity/CycleEntity.kt
  app/src/main/java/com/yongjincompany/hackerthonandroid/features/calendar/utils/CalendarBindingAdapter.kt
  app/src/main/java/com/yongjincompany/hackerthonandroid/features/calendar/utils/CycleDecorator.kt
  app/src/main/java/com/yongjincompany/hackerthonandroid/features/calendar/utils/TodayDecorator.kt
  app/src/main/java/com/yongjincompany/hackerthonandroid/features/calendar/view/CalendarActivity.kt
  app/src/main/java/com/yongjincompany/hackerthonandroid/features/calendar/vm/CalendarViewModel.kt
  app/src/main/res/layout/activity_calendar.xml
Labels: enhancement

#49 📝 :: 소개영상 추가
  README.md
Labels: documentation
